### PR TITLE
Fix screenshot links in RecyclerViewKotlin

### PR DESCRIPTION
**Pull request by joshcurtis**

### CODE REVIEW

**Comment by joshcurtis** [comment]
@googlebot I signed it!

**Comment by joshcurtis** [comment]
@objcode could you take a look?

**Comment by joshcurtis** [comment]
@nfischer maybe?

**Comment by objcode** [comment]
Ahoy!

Before I approve, what was broken? Going to the preview at https://github.com/android/views-widgets-samples/tree/master/RecyclerView it appears the screenshots work with the current path.

Thanks,
Sean

**Comment by joshcurtis** [comment]
Ah, It's the screenshots in the kotlin view that are broken. Sorry for leaving that out of the description
https://github.com/android/views-widgets-samples/tree/8c48ba4/RecyclerViewKotlin#screenshots

**Pull request merged**
